module.exports = {
  name: "Student Success Tracker",
  publisher: "Pansoft",
  cards: [
    {
      type: "Academic",
      source: "./src/cards/StudentSuccessTrackerCard",
      title: "Student Success Tracker",
      displayCardType: "Student Success Tracker Card",
      description:
        "An Experience extension which provides a consolidated view of a student's academic perforamnce for a given term.",
      configuration: {
        client: [
          {
            key: "excellent_performance_color_code",
            label: "Hex color code for excellent performance",
            type: "text",
            require: false,
            default: "#079C34",
          },
          {
            key: "attendance_source",
            label: "Attendance Source(banner/moodle)",
            type: "text",
            require: false,
            default: "banner" 
          },
          {
            key: "grade_source",
            label: "Grade Source(banner/moodle)",
            type: "text",
            require: false,
            default: "banner" 
          },
          {
            key: "satisfactory_performance_color_code",
            label: "Hex color code for satisfactory performance",
            type: "text",
            require: false,
            default: "#F5A327",
          },
          {
            key: "poor_performance_color_code",
            label: "Hex color code for poor performance",
            type: "text",
            require: false,
            default: "#F54927",
          },
          {
            key: "minimum_threshold_for_excellent_performance",
            label: "Minimum threshold for excellent performance",
            type: "text",
            require: true,
            default: "3",
          },
          {
            key: "minimum_threshold_for_satisfactory_performance",
            label: "Minimum threshold for satisfactory performance",
            type: "text",
            require: true,
            default: "2",
          },
          {
            key: "minimum_threshold_for_excellent_attendance",
            label: "Minimum threshold for excellent attendance",
            type: "text",
            require: true,
            default: "80",
          },
          {
            key: "minimum_threshold_for_satisfactory_attendance",
            label: "Minimum threshold for satisfactory attendance",
            type: "text",
            require: true,
            default: "60",
          },
          {
            key: "student_term_courses_pipeline",
            label: "Serverless API name for student term courses",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-term-courses",
          },
          {
            key: "student_gpa_recommendation_pipeline",
            label: "Serverless API name for student GPA recommendation",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-gpa-recommendation",
          },
          {
            key: "student_gpa_recommendation_pipeline",
            label: "Serverless API name for student GPA recommendation",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-gpa-recommendation",
          },
          {
            key: "student_term_courses_pipeline_v2",
            label: "Serverless API name for get student term courses",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-term-courses-v2",
          },
          {
            key: "get_student_course_attendance_banner",
            label: "Serverless API name for get student attendance banner",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-course-attendance-banner",
          },
          {
            key: "get_student_course_attendance_moodle",
            label: "Serverless API name for get student attendance moodle",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-course-attendance-moodle",
          },
          {
            key: "get_student_course_grades_banner",
            label: "Serverless API name for get student grades banner",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-course-grades-banner",
          },
          {
            key: "get_student_course_grades_moodle",
            label: "Serverless API name for get student grades moodle",
            type: "text",
            require: true,
            default: "pansoft-x-get-student-course-grades-moodle",
          },
          {
            key: "moodle_url",
            label: "Moodle URL",
            type: "text",
            require: true,
            default: "https://vidyastu.com/webservice/rest/server.php",
          },
          {
            key: "moodle_ws_token",
            label: "Moodle Token",
            type: "text",
            require: true,
            default: "4d7dc29800b05b61dfd7f8c138e5885f",
          },
          {
            key: "max_gpa",
            label: "Max Gpa",
            type: "text",
            require: true,
            default: "4",
          },
        ],
        server: [
          {
            key: "ethosApiKey",
            label: "Ethos API Key",
            type: "password",
            require: true,
            default: "",
          },
          {
            key: "openAiApiKey",
            label: "Open AI API Key",
            type: "password",
            require: true,
            default: "",
          },
        ],
      },
      pageRoute: {
        route: "/",
        excludeClickSelectors: ["a"],
      },
    },
  ],
  page: {
    source: "./src/page/router.jsx",
    fullWidth: true,
  },
};
